# DO NOT EDIT THIS FILE OR DELETE THIS FILE
# Create a new config.py file in same directory and import, then extend this class.

import os
from typing import Set


class Config(object):
    LOGGER = True
    
    # For sudo plugin
    COMMAND_SUDO = os.environ.get("COMMAND_SUDO", None)
    # set sudo
    SUDO_USERS: Set[int] = set()


class Production(Config):
    LOGGER = False


class Development(Config):
    LOGGER = True
